In [1]:
import os
import re
import shutil
import string
import tensorflow as tf
import pandas as pd
import numpy as np

tf.random.set_seed(42)
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [90]:
# Load email_titles_nlp.keras
model = tf.keras.models.load_model('email_titles_nlp.keras')

# Load TextVectorization
import pickle
from_disk = pickle.load(open("tv_layer.pkl", "rb"))
vectorizer = tf.keras.layers.TextVectorization.from_config(from_disk['config'])
# You have to call `adapt` with some dummy data (BUG in Keras)
vectorizer.adapt(tf.data.Dataset.from_tensor_slices(["xyz"]))
vectorizer.set_vocabulary(from_disk['vocabulary'])

In [ ]:
vectorizer("Checkout Pesanan dengan GoPay Tabungan by Jago Berhasil tanggal 19 September 2024 from:tokopedia.com")

<tf.Tensor: shape=(32,), dtype=int64, numpy=
array([ 21,   4,  19,  14,  25,  26,  16,  17,  20, 380,  38,  15,   7,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0], dtype=int64)>

In [ ]:
model.predict(np.array([vectorizer("✨ New from Google - Learn AI prompting from:m.learn.coursera.org")]), batch_size=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[1.0329195e-05]], dtype=float32)

: 