In [14]:
import os
import re
import shutil
import string
import tensorflow as tf
import pandas as pd
import numpy as np

tf.random.set_seed(42)
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [15]:
# Load email_titles_nlp.keras
model = tf.keras.models.load_model('email_titles_nlp.keras')

# Load TextVectorization
import pickle
from_disk = pickle.load(open("tv_layer.pkl", "rb"))
vectorizer = tf.keras.layers.TextVectorization.from_config(from_disk['config'])
# You have to call `adapt` with some dummy data (BUG in Keras)
vectorizer.adapt(tf.data.Dataset.from_tensor_slices(["xyz"]))
vectorizer.set_vocabulary(from_disk['vocabulary'])

In [16]:
vectorizer("Checkout Pesanan dengan GoPay Tabungan by Jago Berhasil tanggal 19 September 2024 from:tokopedia.com")

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 56,  17,  27,  86, 231,  47, 178,  26,  55, 841, 266,  77,  10,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=int64)>

In [22]:
model.predict(np.array([vectorizer("Your Tuesday evening trip with Uber from:uber.com")]), batch_size=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[0.9999946]], dtype=float32)